- hosts: 172.31.28.44
  become: true
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: present

    - name: Copy index file to Apache server
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Start and enable Apache server
      service:
        name: httpd
        state: started
        enabled: true



