- hosts: 172.31.28.44
  become: true
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: present
      tags:
        - install

    - name: Copy index file to Apache server
      copy:
        src: index.html
        dest: /var/www/html/index.html
      tags:
        - deploy
      notify:
        - restart apache

    - name: Start and enable Apache server
      service:
        name: httpd
        state: started
        enabled: true
      tags:
        - start
        - enable

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted




