---
- hosts: 172.31.28.44
  become: true
  tasks:
    - name: install required packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - docker
        - maven


  


