- hosts: 172.31.28.44
  become: True
  tasks:
    - name: Install Java 17
      dnf:
        name: java-11-amazon-corretto-devel.x86_64
        state: present
    - name: check tar files exist
      stat:
        path: /opt/apache-tomcat-9.0.89
      register: stat_result
    - name: Downloading tomcat tar file
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz
        dest: /opt/
      when: not stat_result.stat.exists
    - name: extract tar file
      unarchive:
        src: /opt/apache-tomcat-9.0.89.tar.gz
        dest: /opt/
        remote_src: yes
  
